---
- name: openshift_project should be defined
  assert:
    that:
    - openshift_project is defined and openshift_project != ''
    msg: "Set the value of 'openshift_project' in the inventory file."

- name: openshift_user should be defined
  assert:
    that:
      - openshift_user is defined and openshift_user != ''
    msg: "Set the value of 'openshift_user' in the inventory file."

- name: openshift_token should be defined
  assert:
    that:
    - openshift_token is defined and openshift_token != ''
    msg: "Set the value of 'openshift_token' in the inventory file."

- name: Check if the oc command is installed
  shell: type oc
  register: oc_result
  ignore_errors: yes

# - name: Ensure OpenShift CLI is installed
#   assert:
#     that:
#     - oc_result.rc == 0
#     msg: "Install the OpenShift CLI (oc)"

- name: Deploy last stable OpenShift CLI 
  become: yes
  unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
    dest: /usr/bin
    remote_src: yes
  when: oc_result.rc != 0


